### ISSUE TITLE
https://github.com/nss-evening-web-development/curriculum/blob/main/src/data/curriculum/client/week-13/next-tutorial.md

### ISSUE THREAD

**Issue by TheByteSizeDev** [nss-evening-web-development/curriculum#26]
**Describe the bug**

NextJS done up and changed their docs on us! A few of the links for this lesson give a 404 now.

**Page URL**
Provide the URL of the page for the issue

[https://nss-evening-curriculum.netlify.app/client/nextjs-tutorial](https://nss-evening-curriculum.netlify.app/client/nextjs-tutorial)

**Expected behavior**

Here are the links that are no longer working:
* [About Next.js](https://nextjs.org/learn/foundations/about-nextjs)
* [From JavaScript to React](https://nextjs.org/learn/foundations/from-javascript-to-react)
* [(OPTIONAL) How Next.js Works](https://nextjs.org/learn/foundations/how-nextjs-works)

I think they reconfigured their docs because I don't see the equivalent pages there anymore.

<img width="590" alt="Screenshot 2023-12-31 at 1 17 57 PM" src="https://github.com/nss-evening-web-development/curriculum/assets/43580474/3a183bd1-8f37-4517-9a5b-310f2f536c9b">

I would like to make suggestions of what to change these links to but I can't remember what we covered previously and it all looks really helpful. Here is the link to the [chapter 1 landing page](https://nextjs.org/learn/react-foundations/what-is-react-and-nextjs).

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by drteresavasquez** [comment]
I've updated the docs. We will revisit when we upgrade to Next 14+
